// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceTimer.Shared.Data;

#nullable disable

namespace RaceTimer.Shared.Migrations
{
    [DbContext(typeof(RaceTimerDbContext))]
    partial class RaceTimerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RaceTimer.Shared.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishDateTimeUTC")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("StartTimeUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipant", b =>
                {
                    b.Property<Guid>("ParticipantID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishDateTimeUTC")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantNr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantID", "RaceID");

                    b.HasIndex("RaceID");

                    b.ToTable("RaceParticipants");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipantTimePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParticipantID")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("PenaltyTime")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("RTPIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RaceID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RaceTimePointId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimePointUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceID");

                    b.HasIndex("RaceTimePointId");

                    b.HasIndex("ParticipantID", "RaceID");

                    b.ToTable("RaceParticipantTimePoints");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceTimePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPenaltyTime")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceID");

                    b.ToTable("RaceTimePoints");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipant", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Participant", "Participant")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipantTimePoint", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantID");

                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceParticipantTimePoints")
                        .HasForeignKey("RaceID");

                    b.HasOne("RaceTimer.Shared.Models.RaceTimePoint", "RaceTimePoint")
                        .WithMany()
                        .HasForeignKey("RaceTimePointId");

                    b.HasOne("RaceTimer.Shared.Models.RaceParticipant", "RaceParticipant")
                        .WithMany("RaceParticipantTimePoints")
                        .HasForeignKey("ParticipantID", "RaceID");

                    b.Navigation("Participant");

                    b.Navigation("Race");

                    b.Navigation("RaceParticipant");

                    b.Navigation("RaceTimePoint");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceTimePoint", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceTimePoints")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.Participant", b =>
                {
                    b.Navigation("RaceParticipations");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.Race", b =>
                {
                    b.Navigation("RaceParticipantTimePoints");

                    b.Navigation("RaceParticipants");

                    b.Navigation("RaceTimePoints");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipant", b =>
                {
                    b.Navigation("RaceParticipantTimePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
