// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceTimerServer.Data;

#nullable disable

namespace RaceTimerServer.Migrations
{
    [DbContext(typeof(RaceTimerDbContext))]
    [Migration("20260524095754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RaceTimer.Shared.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTimeUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipant", b =>
                {
                    b.Property<Guid>("ParticipantID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantID", "RaceID");

                    b.HasIndex("RaceID");

                    b.ToTable("RaceParticipants");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipantTimePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParticipantID")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("PenaltyTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RTPIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RaceID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RaceTimePointId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimePointUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("RaceID");

                    b.HasIndex("RaceTimePointId");

                    b.ToTable("RaceParticipantTimePoints");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceTimePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceID");

                    b.ToTable("RaceTimePoints");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipant", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceParticipantTimePoint", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantID");

                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceParticipantTimePoints")
                        .HasForeignKey("RaceID");

                    b.HasOne("RaceTimer.Shared.Models.RaceTimePoint", "RaceTimePoint")
                        .WithMany()
                        .HasForeignKey("RaceTimePointId");

                    b.Navigation("Participant");

                    b.Navigation("Race");

                    b.Navigation("RaceTimePoint");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.RaceTimePoint", b =>
                {
                    b.HasOne("RaceTimer.Shared.Models.Race", "Race")
                        .WithMany("RaceTimePoints")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceTimer.Shared.Models.Race", b =>
                {
                    b.Navigation("RaceParticipantTimePoints");

                    b.Navigation("RaceParticipants");

                    b.Navigation("RaceTimePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
